services:
  taskapi:
    image: edlcorrea/taskapi:latest
    restart: always
    build: ./
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - 80:8080
    networks:
      - web-taskapi-network   
    volumes:
      - ./src/main/resources/db:/data
networks:
  web-taskapi-network:
    driver: bridge