cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: 3600000
      refresh_factor: 3
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.sqlite.JDBC
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  paths-to-match:
  - "/api/**/v1/**"
  - "/user/**"
  - "/auth/**"
  swagger-ui:
    use-root-path: true