CREATE TABLE IF NOT EXISTS task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL CHECK(priority IN ('LOW', 'MEDIUM', 'HIGH')) DEFAULT 'LOW',
    status TEXT NOT NULL CHECK(status IN ('PENDING', 'COMPLETED')) DEFAULT 'PENDING',
    deadline DATETIME,
    id_user INTEGER,
    FOREIGN KEY (id_user) REFERENCES user(id) ON DELETE CASCADE
);
