name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to DockerHub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Load Environment Variables
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: mvn clean package

    - name: Docker Compose Build
      run: docker compose build

    - name: Push to DockerHub Container Registry
      run: |
       docker tag ${{ secrets.DOCKER_USERNAME }}/taskapi:latest ${{ secrets.DOCKER_USERNAME }}/taskapi:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/taskapi:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/taskapi:latest